var searchData=
[
  ['scene_0',['Scene',['../structrtype_1_1client_1_1Scene.html',1,'rtype::client']]],
  ['score_1',['score',['../structrtype_1_1client_1_1Score.html',1,'rtype::client::Score'],['../structrtype_1_1server_1_1Score.html',1,'rtype::server::Score']]],
  ['security_20and_20integrity_2',['7. Data Security and Integrity',['../md_doc_2TechnicalStudy.html#autotoc_md87',1,'']]],
  ['security_20solutions_3',['7.2 Comparative Study of Security Solutions',['../md_doc_2TechnicalStudy.html#autotoc_md89',1,'']]],
  ['selectable_4',['Selectable',['../structrtype_1_1client_1_1Selectable.html',1,'rtype::client']]],
  ['selectsys_5',['SelectSys',['../classrtype_1_1client_1_1SelectSys.html',1,'rtype::client']]],
  ['serialization_6',['4. BSON Format for Serialization',['../md_doc_2TechnicalStudy.html#autotoc_md78',1,'']]],
  ['server_7',['server',['../md_doc_2NETWORK.html#autotoc_md29',1,'Main Function (Server)'],['../md_doc_2NETWORK.html#autotoc_md28',1,'Server']]],
  ['server_20messages_20strong_8',['1. &lt;strong&gt;Client to Server Messages&lt;/strong&gt;',['../md_doc_2PROTOCOL.html#autotoc_md54',1,'']]],
  ['server_20to_20client_20messages_20strong_9',['2. &lt;strong&gt;Server to Client Messages&lt;/strong&gt;',['../md_doc_2PROTOCOL.html#autotoc_md57',1,'']]],
  ['server_20workflow_3a_10',['Server Workflow:',['../md_doc_2NETWORK.html#autotoc_md47',1,'']]],
  ['sfml_11',['3. SFML',['../md_doc_2TechnicalStudy.html#autotoc_md75',1,'']]],
  ['sfmlobjects_12',['SFMLObjects',['../structrtype_1_1client_1_1SFMLObjects.html',1,'rtype::client']]],
  ['shootsys_13',['ShootSys',['../classrtype_1_1client_1_1ShootSys.html',1,'rtype::client']]],
  ['singleton_14',['Singleton',['../classSingleton.html',1,'']]],
  ['solutions_15',['solutions',['../md_doc_2TechnicalStudy.html#autotoc_md86',1,'6.2 Comparative Study of Storage Solutions'],['../md_doc_2TechnicalStudy.html#autotoc_md89',1,'7.2 Comparative Study of Security Solutions']]],
  ['sound_16',['Sound',['../structrtype_1_1client_1_1Sound.html',1,'rtype::client']]],
  ['sparsearray_17',['SparseArray',['../classSparseArray.html',1,'']]],
  ['spawnqueue_18',['SpawnQueue',['../classSpawnQueue.html',1,'']]],
  ['stage_19',['Stage',['../structrtype_1_1server_1_1Stage.html',1,'rtype::server']]],
  ['storage_20and_20persistence_20',['6. Storage and Persistence',['../md_doc_2TechnicalStudy.html#autotoc_md84',1,'']]],
  ['storage_20solutions_21',['6.2 Comparative Study of Storage Solutions',['../md_doc_2TechnicalStudy.html#autotoc_md86',1,'']]],
  ['store_22',['6.1 Types of Data to Store',['../md_doc_2TechnicalStudy.html#autotoc_md85',1,'']]],
  ['strong_20client_20to_20server_20messages_20strong_23',['1. &lt;strong&gt;Client to Server Messages&lt;/strong&gt;',['../md_doc_2PROTOCOL.html#autotoc_md54',1,'']]],
  ['strong_20hitbox_20strong_20struct_24',['&lt;strong&gt;Hitbox&lt;/strong&gt; (struct)',['../md_doc_2PROTOCOL.html#autotoc_md65',1,'']]],
  ['strong_20message_20details_20strong_25',['strong message details strong',['../md_doc_2PROTOCOL.html#autotoc_md58',1,'&lt;strong&gt;Message Details&lt;/strong&gt;'],['../md_doc_2PROTOCOL.html#autotoc_md55',1,'&lt;strong&gt;Message Details&lt;/strong&gt;']]],
  ['strong_20position_20strong_20struct_26',['&lt;strong&gt;Position&lt;/strong&gt; (struct)',['../md_doc_2PROTOCOL.html#autotoc_md63',1,'']]],
  ['strong_20server_20to_20client_20messages_20strong_27',['2. &lt;strong&gt;Server to Client Messages&lt;/strong&gt;',['../md_doc_2PROTOCOL.html#autotoc_md57',1,'']]],
  ['strong_20velocity_20strong_20struct_28',['&lt;strong&gt;Velocity&lt;/strong&gt; (struct)',['../md_doc_2PROTOCOL.html#autotoc_md64',1,'']]],
  ['struct_29',['struct',['../md_doc_2PROTOCOL.html#autotoc_md65',1,'&lt;strong&gt;Hitbox&lt;/strong&gt; (struct)'],['../md_doc_2PROTOCOL.html#autotoc_md63',1,'&lt;strong&gt;Position&lt;/strong&gt; (struct)'],['../md_doc_2PROTOCOL.html#autotoc_md64',1,'&lt;strong&gt;Velocity&lt;/strong&gt; (struct)']]],
  ['structure_3a_30',['structure:',['../md_doc_2NETWORK.html#autotoc_md44',1,'Structure:'],['../md_doc_2NETWORK.html#autotoc_md42',1,'Structure:']]],
  ['structures_31',['Data Structures',['../md_doc_2PROTOCOL.html#autotoc_md62',1,'']]],
  ['study_32',['study',['../md_doc_2TechnicalStudy.html#autotoc_md74',1,'2.2 Comparative Study'],['../md_doc_2TechnicalStudy.html#autotoc_md77',1,'3.2 Comparative Study'],['../md_doc_2TechnicalStudy.html#autotoc_md80',1,'4.2 Comparative Study'],['../md_doc_2TechnicalStudy.html#autotoc_md83',1,'5.2 Comparative Study']]],
  ['study_20of_20architectures_33',['1.2 Comparative Study of Architectures',['../md_doc_2TechnicalStudy.html#autotoc_md71',1,'']]],
  ['study_20of_20security_20solutions_34',['7.2 Comparative Study of Security Solutions',['../md_doc_2TechnicalStudy.html#autotoc_md89',1,'']]],
  ['study_20of_20storage_20solutions_35',['6.2 Comparative Study of Storage Solutions',['../md_doc_2TechnicalStudy.html#autotoc_md86',1,'']]],
  ['study_20r_20type_36',['Technical and Comparative Study - R-Type',['../md_doc_2TechnicalStudy.html',1,'']]],
  ['submessagehandlersys_37',['SubMessageHandlerSys',['../classrtype_1_1server_1_1SubMessageHandlerSys.html',1,'rtype::server']]],
  ['system_38',['1. ECS Architecture (Entity Component System)',['../md_doc_2TechnicalStudy.html#autotoc_md69',1,'']]],
  ['systems_39',['systems',['../md_doc_2ECS.html#autotoc_md16',1,'Cleaning Systems'],['../md_doc_2ECS.html#autotoc_md19',1,'Permanent Systems'],['../md_doc_2ECS.html#autotoc_md8',1,'Systems']]]
];
