name: Mirroring

on: [ push ]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Clang-Format
        run: |
          sudo apt update
          sudo apt install -y clang-format
      - name: Run Clang-Format on C++ code
        run: |
          find . -name "*.cpp" -o -name "*.h" -o -name "*.hpp" | xargs clang-format --dry-run --Werror
      - name: Apply Clang-Format to C++ code
        run: |
          find . -name "*.cpp" -o -name "*.h" -o -name "*.hpp" | xargs clang-format -i
      - name: Commit and push formatted code
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Apply code formatting using Clang-Format"
          git push origin ${{ github.ref_name }}

  mirroring:
    if: github.repository == 'giordano-pierre/R-Type'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check branch
        run: |
          if [[ "$GITHUB_REF" != "refs/heads/dev" && "$GITHUB_REF" != "refs/heads/main" ]]; then
            echo "This branch is not allowed to push to the target repository."
            exit 1
          fi
      - name: Mirroring Epitech repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            "git@github.com:EpitechPromo2027/B-CPP-500-LYN-5-2-rtype-nathan.baudelin"
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}
