name: Mirroring

on: [ push ]

jobs:
  mirroring:
    if: github.repository == 'giordano-pierre/R-Type'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Mirroring Epitech repository
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            "git@github.com:EpitechPromo2027/B-CPP-500-LYN-5-2-rtype-nathan.baudelinx"
          ssh_private_key:
            ${{ secrets.SSH_PRIVATE_KEY }}